AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Style/MixinGrouping:
  Exclude:
    - "spec/spec_helper.rb"
